version: '3.3'

services:
  app:
    image: lighthouse_service:app
    build: ./app
    restart: unless-stopped
    volumes:
      - ./app/reports:/app/reports
      - ./app/classes:/app/classes
      - ./app/ref:/app/ref
    environment:
      - FLASK_ENV=development
      - FLASK_APP=/app/api.py
      - FLASK_DEBUG=1
      - LC_ALL=C.UTF-8
      - LANG=C.UTF-8
    ports:
      - "9000:9000"
    network_mode: "host"
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
