version: '3.3'

services:
  app:
    image: lighthouse_service:app
    build: ./app
    volumes:
      - ./app/reports:/api/reports
    environment:
      - FLASK_ENV=development
      - FLASK_APP=/api/api.py
      - FLASK_DEBUG=1
      - LC_ALL=C.UTF-8
      - LANG=C.UTF-8
    ports:
      - "9000:9000"
